//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canopy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionsId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime When { get; set; }
        public string Memo { get; set; }
        public bool IsWithdraw { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Category Category { get; set; }
    }
}
